name: Static Code Checks

on:
  pull_request:
    branches:
      - master

jobs:
  bandit:
    name: Check for Security Vulnerabilities
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run bandit against repository
        uses: jpetrucciani/bandit-check@master
        with:
          path: 'src/ramstk'

  format-check:
    name: Check Code Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check code format with docformatter, isort, and yapf
        uses: weibullguy/python-lint-plus@master
        with:
          python-root-list: "src/ramstk"
          use-black: false
          use-yapf: true
          use-isort: true
          use-docformatter: true
          use-pycodestyle: false
          use-pydocstyle: false
          use-mypy: false
          use-pylint: false
          use-flake8: false
          use-mccabe: false
          use-radon: false
          use-rstcheck: false
          use-check-manifest: false
          use-pyroma: false
          extra-black-options: ""
          extra-yapf-options: "-r --style ./setup.cfg"
          extra-isort-options: "--settings-file ./pyproject.toml"
          extra-docformatter-options: ""
          extra-pycodestyle-options: ""
          extra-pydocstyle-options: ""
          extra-mypy-options: ""
          extra-pylint-options: ""
          extra-flake8-options: ""

  style-check:
    name: Check Code Styling
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check code style with pycodestyle and pydocstyle
        uses: weibullguy/python-lint-plus@master
        with:
          python-root-list: "src/ramstk"
          use-black: false
          use-yapf: false
          use-isort: false
          use-docformatter: false
          use-pycodestyle: true
          use-pydocstyle: true
          use-mypy: false
          use-pylint: false
          use-flake8: false
          use-mccabe: false
          use-radon: false
          use-rstcheck: false
          use-check-manifest: false
          use-pyroma: false
          extra-black-options: ""
          extra-yapf-options: ""
          extra-isort-options: ""
          extra-docformatter-options: ""
          extra-pycodestyle-options: "--config=./setup.cfg --count"
          extra-pydocstyle-options: "--count"
          extra-mypy-options: ""
          extra-pylint-options: ""

  type-check:
    name: Check Code Type Hinting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check code type hinting with mypy
        uses: weibullguy/python-lint-plus@master
        with:
          python-root-list: "src/ramstk"
          use-black: false
          use-yapf: false
          use-isort: false
          use-docformatter: false
          use-pycodestyle: false
          use-pydocstyle: false
          use-mypy: true
          use-pylint: false
          use-flake8: false
          use-mccabe: false
          use-radon: false
          use-rstcheck: false
          use-check-manifest: false
          use-pyroma: false
          extra-black-options: ""
          extra-yapf-options: ""
          extra-isort-options: ""
          extra-docformatter-options: ""
          extra-pycodestyle-options: ""
          extra-pydocstyle-options: ""
          extra-mypy-options: "--config-file ./setup.cfg"
          extra-pylint-options: ""
          extra-flake8-options: ""

  lint-check:
    name: Check Code Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint code with pylint
        uses: weibullguy/python-lint-plus@master
        with:
          python-root-list: "src/ramstk"
          use-black: false
          use-yapf: false
          use-isort: false
          use-docformatter: false
          use-pycodestyle: false
          use-pydocstyle: false
          use-mypy: false
          use-pylint: true
          use-flake8: false
          use-mccabe: false
          use-radon: false
          use-rstcheck: false
          use-check-manifest: false
          use-pyroma: false
          extra-black-options: ""
          extra-yapf-options: ""
          extra-isort-options: ""
          extra-docformatter-options: ""
          extra-pycodestyle-options: ""
          extra-pydocstyle-options: ""
          extra-mypy-options: ""
          extra-pylint-options: "-j0 --rcfile=./pyproject.toml --dummy-variables-rgx='__'"
          extra-flake8-options: ""
